# For local development, from your lattice-standard directory, create the environment like this:
#   conda env create -y -f conda.yaml
#   conda activate lattice-standard
#
name: lattice-standard

channels:
  - conda-forge
  - nodefaults

dependencies:
  - docutils
  - python
  - myst-parser
  - pip
  - pybtex
  - pygments
  - recommonmark
  - sphinx
  - sphinx-autobuild
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-design
  - sphinxcontrib-bibtex
  - sphinxcontrib-svg2pdfconverter-with-all
  - sphinxcontrib-napoleon
# - sphinx_rtd_theme
